version: "2"
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend/pyapp
    ports:
      - 8000:8000
